#!/usr/bin/bash

echo =================================================================
echo comma boot logo & bootanimation change by lepro3
echo =================================================================
echo dd if=./splash.img of=/dev/block/bootdevice/by-name/splash
echo mount -o rw,remount /system
echo cp ./bootanimation.zip /system/media/
