#!/usr/bin/bash

echo =================================================================
echo comma boot logo & bootanimation change by lepro3
echo =================================================================
dd if=./splash.img of=/dev/block/bootdevice/by-name/splash
mount -o rw,remount /system
cp ./bootanimation.zip /system/media/
